## These properties configure your NeoForge mod.  Many values from this file
## are automatically substituted into the neoforge.mods.toml file.  See
## NeoForged documentation for more details on gradle.properties and mod
## configuration【840203598704741†L158-L171】.

# Target Minecraft version and allowed version range
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)

# Target NeoForge version and allowed version range
neo_version=21.1.72
neo_version_range=[21.1,21.2)

# Your mod's unique identifier and display name.  The mod ID should be all
# lowercase and match the value used in the @Mod annotation【840203598704741†L118-L126】.
mod_id=boss_ai
mod_name=Boss AI

# Human‑readable version of your mod.  Update this as you release new
# versions.
mod_version=0.1.0

# Java package of your mod.  This should match the top level package of
# your source files【840203598704741†L150-L152】.
mod_group_id=com.github.silbaram

# Optional metadata displayed in the mods menu
mod_authors=silbaram
mod_description=Boss AI mod with lightweight AI based behaviours.
mod_license=MIT

org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8 -Dboss_ai.dev=false -Dboss_ai.logging.locale=ko
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

